### ISSUE TITLE
How to reset when error?

### ISSUE THREAD

**Issue by novayadi85** [synapsestudios/react-drop-n-crop#21]
When I try to upload the get error..
How to reset the dropzone ??

thx

**Comment by bobeagan** [comment]
This issue does not contain enough information.  Feel free to re-open with more details if you would like help.

**Comment by novayadi85** [comment]
I mean how to remove or change my image in drop area?
I try to do that because something happend in server side. 

Do you get what i mean?? or still not enough information??

**Comment by novayadi85** [comment]
Why this is issue is closed? I dont have the good answer for it.

**Comment by bobeagan** [comment]
What about refreshing the page?

You're responsible for writing the component that uses the crop and drop, and passing in the `value` which is where the error information is stored.

You can either upload a file that doesn't have errors, or you can write a way to clear the errors by updating the state of whatever your component is that's using dropncrop

https://github.com/synapsestudios/react-drop-n-crop#using-with-an-es6-class-and-react-component-state
