### ISSUE TITLE
Getting the warning in the browser

### ISSUE THREAD

**Issue by nvnvenki** [synapsestudios/react-drop-n-crop#7]
Warning: You are manually calling a React.PropTypes validation function for the `zoom` prop on `ReactCropper`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by chrisheninger** [comment]
Hi @nvnvenki,

A heads up– this project is still in early stages... use with caution!

The propType validation error you are seeing appears to be thrown a layer under our `DropNCrop` component, at the `ReactCropper` level.

Since this is out of my immediate control, I'm marking the issue as closed.
