### ISSUE TITLE
Repo settings updates

### ISSUE THREAD

**Issue by chrisheninger** [synapsestudios/react-drop-n-crop#8]
I don't have permissions, need @bobeagan.

- [x] Add description `An opinionated implementation of react-dropzone and react-cropper`
- [x] Add Tags `react javascript drop-n-crop react-drop-n-crop dropzone react-dropzone cropper react-cropper drag-and-drop crop-image image-cropper crop image`

**Comment by bobeagan** [comment]
Should be good to go, I also updated the website with the demo url.  Double check that I didn't miss anything and then you can probably close this.

**Comment by chrisheninger** [comment]
👍
